# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "764bafd07482a23d32f22da587e91651"
name = "Book App"
handle = "book-app-8"
application_url = "https://kinase-satisfaction-untitled-communicate.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://kinase-satisfaction-untitled-communicate.trycloudflare.com/auth/callback", "https://kinase-satisfaction-untitled-communicate.trycloudflare.com/auth/shopify/callback", "https://kinase-satisfaction-untitled-communicate.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
